### ISSUE TITLE
How to keep cache coherence 

### ISSUE THREAD

**Issue by MagicalBomb** [latolukasz/beeorm#8]
Hi,
I noticed cache in redis and local have no expiration time, so I wonder how to keep cache coherence in BeeORM
Maybe I should clear redis and local cache periodically?
Actually, I wonder if there are best practices
BeeORM really a amazing project, Thanks

**Comment by latolukasz** [comment]
Hi, you mean cache used to store Entities data?
If yes, then no, there is no need to define TTL for this data because BeeORM tracks all entity data and clears/update cache data if needed. Idea is that you should not worry about cache coherence at all. Simply flush entity and let BeeORM to update cache.
